/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.progmulti.proyectofinal.sistema.taller.Vistas;

import java.awt.Color;

/**
 *
 * @author Victor Alejandro
 */
public class Equipos extends javax.swing.JFrame {

    /**
     * Creates new form Equipos
     */
    public Equipos() {
        this.setUndecorated(true);
        this.setBackground(new Color(0, 0, 0, 0));
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Equipos");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneles1 = new com.progmulti.proyectofinal.sistema.taller.Vistas.paneles();
        paneles2 = new com.progmulti.proyectofinal.sistema.taller.Vistas.paneles();
        tbBusqueda = new javax.swing.JTextField();
        btnIngresar = new com.progmulti.proyectofinal.sistema.taller.Vistas.botones();
        jScrollPane2 = new javax.swing.JScrollPane();
        Registros = new com.progmulti.proyectofinal.sistema.taller.Vistas.tablas();
        jLabel8 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        btnBuscar = new com.progmulti.proyectofinal.sistema.taller.Vistas.botones();
        btnEntregar = new com.progmulti.proyectofinal.sistema.taller.Vistas.botones();
        btnEliminar = new com.progmulti.proyectofinal.sistema.taller.Vistas.botones();
        btnVer = new com.progmulti.proyectofinal.sistema.taller.Vistas.botones();
        btnInicio = new com.progmulti.proyectofinal.sistema.taller.Vistas.botones();
        btnMinimizar = new com.progmulti.proyectofinal.sistema.taller.Vistas.botones();
        btnCerrar = new com.progmulti.proyectofinal.sistema.taller.Vistas.botones();
        btnModelos = new com.progmulti.proyectofinal.sistema.taller.Vistas.botones();
        btnTipo = new com.progmulti.proyectofinal.sistema.taller.Vistas.botones();
        btnMarcas = new com.progmulti.proyectofinal.sistema.taller.Vistas.botones();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        paneles1.setBackground(new java.awt.Color(0, 0, 0));

        paneles2.setBackground(new java.awt.Color(18, 18, 18));

        tbBusqueda.setBackground(new java.awt.Color(18, 18, 18));
        tbBusqueda.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        tbBusqueda.setForeground(new java.awt.Color(255, 255, 255));
        tbBusqueda.setBorder(null);

        btnIngresar.setBackground(new java.awt.Color(0, 204, 102));
        btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar.setText("Agregar");
        btnIngresar.setBorderColor(new java.awt.Color(0, 204, 102));
        btnIngresar.setColor(new java.awt.Color(0, 204, 102));
        btnIngresar.setColorClick(new java.awt.Color(0, 153, 102));
        btnIngresar.setColorOver(new java.awt.Color(0, 153, 102));
        btnIngresar.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        btnIngresar.setRadio(40);
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        Registros.setBackground(new java.awt.Color(18, 18, 18));
        Registros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Cliente", "Tipo", "Marca", "Modelo", "Problema", "Observaciones", "Resultado", "Fecha", "Estado", "Monto"
            }
        ));
        Registros.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        Registros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistrosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Registros);

        jLabel8.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(3, 218, 198));
        jLabel8.setText("Equipos Ingresados");

        jSeparator5.setBackground(new java.awt.Color(3, 218, 198));
        jSeparator5.setForeground(new java.awt.Color(3, 218, 198));

        btnBuscar.setBackground(new java.awt.Color(3, 218, 198));
        btnBuscar.setForeground(new java.awt.Color(0, 51, 51));
        btnBuscar.setText("Buscar");
        btnBuscar.setBorderColor(new java.awt.Color(3, 218, 198));
        btnBuscar.setColor(new java.awt.Color(3, 218, 198));
        btnBuscar.setColorClick(new java.awt.Color(0, 204, 204));
        btnBuscar.setColorOver(new java.awt.Color(0, 204, 204));
        btnBuscar.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        btnBuscar.setRadio(40);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnEntregar.setBackground(new java.awt.Color(0, 102, 255));
        btnEntregar.setForeground(new java.awt.Color(255, 255, 255));
        btnEntregar.setText("Entregar");
        btnEntregar.setBorderColor(new java.awt.Color(0, 102, 255));
        btnEntregar.setColor(new java.awt.Color(0, 102, 255));
        btnEntregar.setColorClick(new java.awt.Color(0, 102, 204));
        btnEntregar.setColorOver(new java.awt.Color(0, 102, 204));
        btnEntregar.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        btnEntregar.setRadio(40);
        btnEntregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntregarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(255, 0, 0));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorderColor(new java.awt.Color(255, 0, 0));
        btnEliminar.setColor(new java.awt.Color(255, 0, 0));
        btnEliminar.setColorClick(new java.awt.Color(204, 0, 0));
        btnEliminar.setColorOver(new java.awt.Color(204, 0, 0));
        btnEliminar.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        btnEliminar.setRadio(40);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnVer.setBackground(new java.awt.Color(255, 204, 0));
        btnVer.setForeground(new java.awt.Color(255, 255, 255));
        btnVer.setText("Ver");
        btnVer.setBorderColor(new java.awt.Color(255, 204, 0));
        btnVer.setColor(new java.awt.Color(255, 204, 0));
        btnVer.setColorClick(new java.awt.Color(255, 153, 0));
        btnVer.setColorOver(new java.awt.Color(255, 153, 0));
        btnVer.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        btnVer.setRadio(40);
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneles2Layout = new javax.swing.GroupLayout(paneles2);
        paneles2.setLayout(paneles2Layout);
        paneles2Layout.setHorizontalGroup(
            paneles2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneles2Layout.createSequentialGroup()
                .addGroup(paneles2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneles2Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel8))
                    .addGroup(paneles2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(paneles2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(paneles2Layout.createSequentialGroup()
                                .addGroup(paneles2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tbBusqueda)
                                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnVer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEntregar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 879, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        paneles2Layout.setVerticalGroup(
            paneles2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneles2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneles2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(paneles2Layout.createSequentialGroup()
                        .addComponent(tbBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneles2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEntregar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnVer, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );

        btnInicio.setBackground(new java.awt.Color(3, 218, 198));
        btnInicio.setForeground(new java.awt.Color(0, 51, 51));
        btnInicio.setText("Inicio");
        btnInicio.setBorderColor(new java.awt.Color(3, 218, 198));
        btnInicio.setColor(new java.awt.Color(3, 218, 198));
        btnInicio.setColorClick(new java.awt.Color(0, 204, 204));
        btnInicio.setColorOver(new java.awt.Color(0, 204, 204));
        btnInicio.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        btnInicio.setRadio(40);
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        btnMinimizar.setBackground(new java.awt.Color(255, 255, 0));
        btnMinimizar.setBorderColor(new java.awt.Color(255, 255, 0));
        btnMinimizar.setColor(new java.awt.Color(255, 255, 0));
        btnMinimizar.setColorClick(new java.awt.Color(255, 204, 0));
        btnMinimizar.setColorOver(new java.awt.Color(255, 204, 0));
        btnMinimizar.setRadio(100);
        btnMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizarActionPerformed(evt);
            }
        });

        btnCerrar.setBackground(new java.awt.Color(255, 0, 0));
        btnCerrar.setBorderColor(new java.awt.Color(255, 0, 0));
        btnCerrar.setColor(new java.awt.Color(255, 0, 0));
        btnCerrar.setColorClick(new java.awt.Color(204, 0, 0));
        btnCerrar.setColorOver(new java.awt.Color(204, 0, 0));
        btnCerrar.setRadio(100);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        btnModelos.setBackground(new java.awt.Color(3, 218, 198));
        btnModelos.setForeground(new java.awt.Color(0, 51, 51));
        btnModelos.setText("Modelos");
        btnModelos.setBorderColor(new java.awt.Color(3, 218, 198));
        btnModelos.setColor(new java.awt.Color(3, 218, 198));
        btnModelos.setColorClick(new java.awt.Color(0, 204, 204));
        btnModelos.setColorOver(new java.awt.Color(0, 204, 204));
        btnModelos.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        btnModelos.setRadio(40);
        btnModelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModelosActionPerformed(evt);
            }
        });

        btnTipo.setBackground(new java.awt.Color(3, 218, 198));
        btnTipo.setForeground(new java.awt.Color(0, 51, 51));
        btnTipo.setText("Tipos");
        btnTipo.setBorderColor(new java.awt.Color(3, 218, 198));
        btnTipo.setColor(new java.awt.Color(3, 218, 198));
        btnTipo.setColorClick(new java.awt.Color(0, 204, 204));
        btnTipo.setColorOver(new java.awt.Color(0, 204, 204));
        btnTipo.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        btnTipo.setRadio(40);
        btnTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoActionPerformed(evt);
            }
        });

        btnMarcas.setBackground(new java.awt.Color(3, 218, 198));
        btnMarcas.setForeground(new java.awt.Color(0, 51, 51));
        btnMarcas.setText("Marcas");
        btnMarcas.setBorderColor(new java.awt.Color(3, 218, 198));
        btnMarcas.setColor(new java.awt.Color(3, 218, 198));
        btnMarcas.setColorClick(new java.awt.Color(0, 204, 204));
        btnMarcas.setColorOver(new java.awt.Color(0, 204, 204));
        btnMarcas.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        btnMarcas.setRadio(40);
        btnMarcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarcasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneles1Layout = new javax.swing.GroupLayout(paneles1);
        paneles1.setLayout(paneles1Layout);
        paneles1Layout.setHorizontalGroup(
            paneles1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneles1Layout.createSequentialGroup()
                .addGroup(paneles1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(paneles1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(paneles2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneles1Layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMarcas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModelos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 261, Short.MAX_VALUE)
                        .addComponent(btnMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        paneles1Layout.setVerticalGroup(
            paneles1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneles1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneles1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneles1Layout.createSequentialGroup()
                        .addGroup(paneles1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneles1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnModelos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMarcas, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(paneles2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneles1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneles1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        Ingreso ing = new Ingreso();
        ing.show();
        this.dispose();
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void RegistrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrosMouseClicked
        /*
        fila = Registros.rowAtPoint(evt.getPoint());
        codigo = Long.valueOf(String.valueOf(Registros.getValueAt(fila, 0)));
        tbNombre.setText(String.valueOf(Registros.getValueAt(fila, 1)));
        tbCorreo.setText(String.valueOf(Registros.getValueAt(fila, 2)));
        tbTel.setText(String.valueOf(Registros.getValueAt(fila, 3)));
        tbClave.setText(String.valueOf(Registros.getValueAt(fila, 4)));
        */
    }//GEN-LAST:event_RegistrosMouseClicked

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        Menu menu = new Menu();
        menu.show();
        this.dispose();
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizarActionPerformed
        this.setState(ICONIFIED);
    }//GEN-LAST:event_btnMinimizarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
         /*
        String busqueda = tbBusqueda.getText();
        Busqueda(busqueda);
        Limpiar();*/
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEntregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntregarActionPerformed
       Entrega ent = new Entrega();
       ent.show();
       this.dispose();
    }//GEN-LAST:event_btnEntregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerActionPerformed

    private void btnModelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModelosActionPerformed
        Modelos model = new Modelos();
        model.show();
    }//GEN-LAST:event_btnModelosActionPerformed

    private void btnTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoActionPerformed
        Tipos tipo = new Tipos();
        tipo.show();
    }//GEN-LAST:event_btnTipoActionPerformed

    private void btnMarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarcasActionPerformed
       Marcas mar = new Marcas();
       mar.show();
    }//GEN-LAST:event_btnMarcasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Equipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Equipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Equipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Equipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Equipos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.progmulti.proyectofinal.sistema.taller.Vistas.tablas Registros;
    private com.progmulti.proyectofinal.sistema.taller.Vistas.botones btnBuscar;
    private com.progmulti.proyectofinal.sistema.taller.Vistas.botones btnCerrar;
    private com.progmulti.proyectofinal.sistema.taller.Vistas.botones btnEliminar;
    private com.progmulti.proyectofinal.sistema.taller.Vistas.botones btnEntregar;
    private com.progmulti.proyectofinal.sistema.taller.Vistas.botones btnIngresar;
    private com.progmulti.proyectofinal.sistema.taller.Vistas.botones btnInicio;
    private com.progmulti.proyectofinal.sistema.taller.Vistas.botones btnMarcas;
    private com.progmulti.proyectofinal.sistema.taller.Vistas.botones btnMinimizar;
    private com.progmulti.proyectofinal.sistema.taller.Vistas.botones btnModelos;
    private com.progmulti.proyectofinal.sistema.taller.Vistas.botones btnTipo;
    private com.progmulti.proyectofinal.sistema.taller.Vistas.botones btnVer;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator5;
    private com.progmulti.proyectofinal.sistema.taller.Vistas.paneles paneles1;
    private com.progmulti.proyectofinal.sistema.taller.Vistas.paneles paneles2;
    private javax.swing.JTextField tbBusqueda;
    // End of variables declaration//GEN-END:variables
}
