/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.progmulti.proyectofinal.sistema.taller.Vistas;

import java.awt.Color;

/**
 *
 * @author Victor Alejandro
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        this.setUndecorated(true);
        this.setBackground(new Color(0, 0, 0, 0));
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Menu");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneles1 = new com.progmulti.proyectofinal.sistema.taller.Vistas.paneles();
        btnMinimizar = new com.progmulti.proyectofinal.sistema.taller.Vistas.botones();
        btnCerrar = new com.progmulti.proyectofinal.sistema.taller.Vistas.botones();
        paneles2 = new com.progmulti.proyectofinal.sistema.taller.Vistas.paneles();
        btnUsuarios = new com.progmulti.proyectofinal.sistema.taller.Vistas.botones();
        btnClientes = new com.progmulti.proyectofinal.sistema.taller.Vistas.botones();
        btnIngreso = new com.progmulti.proyectofinal.sistema.taller.Vistas.botones();
        btnServicio = new com.progmulti.proyectofinal.sistema.taller.Vistas.botones();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        paneles1.setBackground(new java.awt.Color(0, 0, 0));

        btnMinimizar.setBackground(new java.awt.Color(255, 255, 0));
        btnMinimizar.setBorderColor(new java.awt.Color(255, 255, 0));
        btnMinimizar.setColor(new java.awt.Color(255, 255, 0));
        btnMinimizar.setColorClick(new java.awt.Color(255, 204, 0));
        btnMinimizar.setColorOver(new java.awt.Color(255, 204, 0));
        btnMinimizar.setRadio(100);
        btnMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizarActionPerformed(evt);
            }
        });

        btnCerrar.setBackground(new java.awt.Color(255, 0, 0));
        btnCerrar.setBorderColor(new java.awt.Color(255, 0, 0));
        btnCerrar.setColor(new java.awt.Color(255, 0, 0));
        btnCerrar.setColorClick(new java.awt.Color(204, 0, 0));
        btnCerrar.setColorOver(new java.awt.Color(204, 0, 0));
        btnCerrar.setRadio(100);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        paneles2.setBackground(new java.awt.Color(18, 18, 18));

        btnUsuarios.setBackground(new java.awt.Color(3, 218, 198));
        btnUsuarios.setForeground(new java.awt.Color(0, 51, 51));
        btnUsuarios.setText("Usuarios");
        btnUsuarios.setBorderColor(new java.awt.Color(3, 218, 198));
        btnUsuarios.setColor(new java.awt.Color(3, 218, 198));
        btnUsuarios.setColorClick(new java.awt.Color(0, 204, 204));
        btnUsuarios.setColorOver(new java.awt.Color(0, 204, 204));
        btnUsuarios.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        btnUsuarios.setRadio(40);
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });

        btnClientes.setBackground(new java.awt.Color(3, 218, 198));
        btnClientes.setForeground(new java.awt.Color(0, 51, 51));
        btnClientes.setText("Clientes");
        btnClientes.setBorderColor(new java.awt.Color(3, 218, 198));
        btnClientes.setColor(new java.awt.Color(3, 218, 198));
        btnClientes.setColorClick(new java.awt.Color(0, 204, 204));
        btnClientes.setColorOver(new java.awt.Color(0, 204, 204));
        btnClientes.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        btnClientes.setRadio(40);
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });

        btnIngreso.setBackground(new java.awt.Color(3, 218, 198));
        btnIngreso.setForeground(new java.awt.Color(0, 51, 51));
        btnIngreso.setText("Equipos");
        btnIngreso.setBorderColor(new java.awt.Color(3, 218, 198));
        btnIngreso.setColor(new java.awt.Color(3, 218, 198));
        btnIngreso.setColorClick(new java.awt.Color(0, 204, 204));
        btnIngreso.setColorOver(new java.awt.Color(0, 204, 204));
        btnIngreso.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        btnIngreso.setRadio(40);
        btnIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresoActionPerformed(evt);
            }
        });

        btnServicio.setBackground(new java.awt.Color(3, 218, 198));
        btnServicio.setForeground(new java.awt.Color(0, 51, 51));
        btnServicio.setText("Reportes");
        btnServicio.setBorderColor(new java.awt.Color(3, 218, 198));
        btnServicio.setColor(new java.awt.Color(3, 218, 198));
        btnServicio.setColorClick(new java.awt.Color(0, 204, 204));
        btnServicio.setColorOver(new java.awt.Color(0, 204, 204));
        btnServicio.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        btnServicio.setRadio(40);

        javax.swing.GroupLayout paneles2Layout = new javax.swing.GroupLayout(paneles2);
        paneles2.setLayout(paneles2Layout);
        paneles2Layout.setHorizontalGroup(
            paneles2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneles2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        paneles2Layout.setVerticalGroup(
            paneles2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneles2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneles2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout paneles1Layout = new javax.swing.GroupLayout(paneles1);
        paneles1.setLayout(paneles1Layout);
        paneles1Layout.setHorizontalGroup(
            paneles1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneles1Layout.createSequentialGroup()
                .addContainerGap(235, Short.MAX_VALUE)
                .addComponent(paneles2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(216, 216, 216)
                .addComponent(btnMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        paneles1Layout.setVerticalGroup(
            paneles1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneles1Layout.createSequentialGroup()
                .addGroup(paneles1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneles1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(paneles1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(paneles1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(paneles2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(634, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneles1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneles1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizarActionPerformed
        this.setState(ICONIFIED);
    }//GEN-LAST:event_btnMinimizarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        Usuarios usuario = new Usuarios();
        usuario.show();
        this.dispose();
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        Clientes cliente = new Clientes();
        cliente.show();
        this.dispose();
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresoActionPerformed
        Equipos equipo = new Equipos();
        equipo.show();
        this.dispose();
    }//GEN-LAST:event_btnIngresoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.progmulti.proyectofinal.sistema.taller.Vistas.botones btnCerrar;
    private com.progmulti.proyectofinal.sistema.taller.Vistas.botones btnClientes;
    private com.progmulti.proyectofinal.sistema.taller.Vistas.botones btnIngreso;
    private com.progmulti.proyectofinal.sistema.taller.Vistas.botones btnMinimizar;
    private com.progmulti.proyectofinal.sistema.taller.Vistas.botones btnServicio;
    private com.progmulti.proyectofinal.sistema.taller.Vistas.botones btnUsuarios;
    private com.progmulti.proyectofinal.sistema.taller.Vistas.paneles paneles1;
    private com.progmulti.proyectofinal.sistema.taller.Vistas.paneles paneles2;
    // End of variables declaration//GEN-END:variables
}
